
// Objective-C API for talking to the following Go packages
//
//	github.com/dabankio/wallet-core/bip39
//	github.com/dabankio/wallet-core/bip44
//	github.com/dabankio/wallet-core/core/btc
//	github.com/dabankio/wallet-core/core/eth
//	github.com/dabankio/wallet-core/core/omni
//	github.com/dabankio/wallet-core/wallet
//	github.com/dabankio/wallet-core/core/bbc
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Bip39_FRAMEWORK_H__
#define __Bip39_FRAMEWORK_H__

#include "Bip39.objc.h"
#include "Bip44.objc.h"
#include "Btc.objc.h"
#include "Eth.objc.h"
#include "Omni.objc.h"
#include "Wallet.objc.h"
#include "Bbc.objc.h"
#include "Universe.objc.h"

#endif
