// Objective-C API for talking to github.com/dabankio/wallet-core/bip44 Go package.
//   gobind -lang=objc github.com/dabankio/wallet-core/bip44
//
// File is generated by gobind. Do not edit.

#ifndef __Bip44_H__
#define __Bip44_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Bip44AdditionalDeriveParam;
@protocol Bip44Deriver;
@class Bip44Deriver;

@protocol Bip44Deriver <NSObject>
- (NSString* _Nonnull)deriveAddress:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)derivePrivateKey:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)derivePublicKey:(NSError* _Nullable* _Nullable)error;
@end

/**
 * AdditionalDeriveParam 额外的推导参数
 */
@interface Bip44AdditionalDeriveParam : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long accountIndex;
@property (nonatomic) long changeType;
@property (nonatomic) long index;
@end

/**
 * ChangeTypeExternal 通常用于收款，对外部可见
 */
FOUNDATION_EXPORT const int64_t Bip44ChangeTypeExternal;
/**
 * ChangeTypeInternal 通常用于找零，通常不对外可见
 */
FOUNDATION_EXPORT const int64_t Bip44ChangeTypeInternal;
FOUNDATION_EXPORT NSString* _Nonnull const Bip44FullPathFormat;
FOUNDATION_EXPORT NSString* _Nonnull const Bip44FullPathFormat4;
FOUNDATION_EXPORT NSString* _Nonnull const Bip44Password;
FOUNDATION_EXPORT NSString* _Nonnull const Bip44PathFormat;

// skipped function GetCoinDerivationPath with unsupported parameter or return types


// skipped function GetCoinType with unsupported parameter or return types


// skipped function GetDerivePath with unsupported parameter or return types


@class Bip44Deriver;

/**
 * Deriver derives address/publicKey/privateKey
 */
@interface Bip44Deriver : NSObject <goSeqRefInterface, Bip44Deriver> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * DeriveAddress derives the account address of the derivation path.
 */
- (NSString* _Nonnull)deriveAddress:(NSError* _Nullable* _Nullable)error;
/**
 * DerivePrivateKey derives the private key of the derivation path.
 */
- (NSString* _Nonnull)derivePrivateKey:(NSError* _Nullable* _Nullable)error;
/**
 * DerivePublicKey derives the public key of the derivation path.
 */
- (NSString* _Nonnull)derivePublicKey:(NSError* _Nullable* _Nullable)error;
@end

#endif
