// Objective-C API for talking to github.com/dabankio/wallet-core/core/bbc Go package.
//   gobind -lang=objc github.com/dabankio/wallet-core/core/bbc
//
// File is generated by gobind. Do not edit.

#ifndef __Bbc_H__
#define __Bbc_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Bip44.objc.h"

@class BbcKeyInfo;
@class BbcTxBuilder;

/**
 * KeyInfo 私钥，公钥，地址
 */
@interface BbcKeyInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull privateKey;
@property (nonatomic) NSString* _Nonnull publicKey;
@property (nonatomic) NSString* _Nonnull address;
@end

/**
 * TxBuilder transaction builder
 */
@interface BbcTxBuilder : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewTxBuilder new 一个transaction builder
 */
- (nullable instancetype)init;
// skipped field TxBuilder.TXBuilder with unsupported type: *github.com/lomocoin/gobbc.TXBuilder

/**
 * AddInput 参考listunspent,确保输入金额满足amount
 */
- (BbcTxBuilder* _Nullable)addInput:(NSString* _Nullable)txid vout:(int8_t)vout;
/**
 * Build 构造交易,返回hex编码的tx
 */
- (NSString* _Nonnull)build:(NSError* _Nullable* _Nullable)error;
/**
 * SetAddress 转账地址,目前只支持公钥地址
 */
- (BbcTxBuilder* _Nullable)setAddress:(NSString* _Nullable)add;
/**
 * SetAmount 转账金额
 */
- (BbcTxBuilder* _Nullable)setAmount:(double)amount;
/**
 * SetAnchor 锚定分支id
 */
- (BbcTxBuilder* _Nullable)setAnchor:(NSString* _Nullable)anchor;
/**
 * SetData 原始data设置,参考 UtilDataEncoding
 */
- (BbcTxBuilder* _Nullable)setData:(NSData* _Nullable)data;
/**
 * SetDataWithUUID 指定uuid,timestamp,data
 */
- (BbcTxBuilder* _Nullable)setDataWithUUID:(NSString* _Nullable)p0 timestamp:(int64_t)timestamp data:(NSString* _Nullable)data;
/**
 * SetFee 手续费，目前0.01，如果带data则0.03, 额外需咨询BBC
 */
- (BbcTxBuilder* _Nullable)setFee:(double)fee;
/**
 * SetLockUntil lock until
 */
- (BbcTxBuilder* _Nullable)setLockUntil:(long)lockUntil;
/**
 * SetStringData 自动编码数据,自动生成uuid和时间戳
 */
- (BbcTxBuilder* _Nullable)setStringData:(NSString* _Nullable)data;
/**
 * SetTimestamp 交易时间戳
 */
- (BbcTxBuilder* _Nullable)setTimestamp:(long)timestamp;
/**
 * SetVersion 当前版本 1
 */
- (BbcTxBuilder* _Nullable)setVersion:(long)v;
@end

/**
 * Address2pubk 将地址转换为公钥
 */
FOUNDATION_EXPORT NSString* _Nonnull BbcAddress2pubk(NSString* _Nullable address, NSError* _Nullable* _Nullable error);

/**
 * DecodeTX 解析原始交易（使用JSON RPC createtransaction 创建的交易）,
 */
FOUNDATION_EXPORT NSString* _Nonnull BbcDecodeTX(NSString* _Nullable rawTX, NSError* _Nullable* _Nullable error);

/**
 * DeriveKey 该函数后面3个参数无效，等同于 DeriveKeySimple，仅保留
 */
FOUNDATION_EXPORT BbcKeyInfo* _Nullable BbcDeriveKey(NSData* _Nullable seed, long accountIndex, long changeType, long index, NSError* _Nullable* _Nullable error);

/**
 * DeriveKeySimple 推导路径 m/44'/%d'
 */
FOUNDATION_EXPORT BbcKeyInfo* _Nullable BbcDeriveKeySimple(NSData* _Nullable seed, NSError* _Nullable* _Nullable error);

/**
 * NewBip44Deriver 根据种子获取bip44推导
accountIndex 账户索引，以0开始
changeType 0:外部使用， 1:找零， 通常使用0,BBC通常找零到发送地址
index 地址索引，以0开始
 */
FOUNDATION_EXPORT id<Bip44Deriver> _Nullable BbcNewBip44Deriver(NSData* _Nullable seed, long accountIndex, long changeType, long index, NSError* _Nullable* _Nullable error);

// skipped function NewCoin with unsupported parameter or return types


/**
 * NewSimpleBip44Deriver 根据种子获取bip44推导,仅推导1个
 */
FOUNDATION_EXPORT id<Bip44Deriver> _Nullable BbcNewSimpleBip44Deriver(NSData* _Nullable seed, NSError* _Nullable* _Nullable error);

/**
 * NewTxBuilder new 一个transaction builder
 */
FOUNDATION_EXPORT BbcTxBuilder* _Nullable BbcNewTxBuilder(void);

/**
 * ParsePrivateKey 解析私钥，返回 privateKey,publicKey,address
 */
FOUNDATION_EXPORT BbcKeyInfo* _Nullable BbcParsePrivateKey(NSString* _Nullable privateKey, NSError* _Nullable* _Nullable error);

/**
 * SignWithPrivateKey 使用私钥对原始交易进行签名,
关于templateData的使用参考 https://github.com/lomocoin/gobbc/blob/d51d596fa310a5778e3d11eb59bc66d1a6a5e3d6/transaction.go#L197 （SignWithPrivateKey部分）
参考测试用例 qa/bbc/example_bbc_test.go
 */
FOUNDATION_EXPORT NSString* _Nonnull BbcSignWithPrivateKey(NSString* _Nullable rawTX, NSString* _Nullable templateData, NSString* _Nullable privateKey, NSError* _Nullable* _Nullable error);

#endif
